-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 11:03:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db01restaurante
-- -----------------------------------------------------
-- EJERCICIO EN CLASE: CREAR UN ERD RESTAURANTE
-- 
-- Considere las siguientes entidades:
-- 
-- Clientes:
--   Nombre
--   Apellido
--   Fecha de nacimiento
-- 
-- Ordenes:
--   Fecha de ordenes
--   Total cuenta
--   Cliente
--   Mesa
-- 
-- Mesas:
--   Nombre
--   Descripción
--   Mesero
-- 
-- Mesero:
--   Nombre
--   Apellido
-- 
-- Platos:
--   Nombre
--   Descripción
--   Precio
--   Orden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db01restaurante` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db01restaurante` ;

-- -----------------------------------------------------
-- Table `db01restaurante`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db01restaurante`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db01restaurante`.`Meseros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db01restaurante`.`Meseros` (
  `idMeseros` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMeseros`),
  UNIQUE INDEX `idMeseros_UNIQUE` (`idMeseros` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db01restaurante`.`Mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db01restaurante`.`Mesas` (
  `idMesas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `Meseros_idMeseros` INT NOT NULL,
  PRIMARY KEY (`idMesas`, `Meseros_idMeseros`),
  UNIQUE INDEX `idMesas_UNIQUE` (`idMesas` ASC) VISIBLE,
  INDEX `fk_Mesas_Meseros1_idx` (`Meseros_idMeseros` ASC) VISIBLE,
  CONSTRAINT `fk_Mesas_Meseros1`
    FOREIGN KEY (`Meseros_idMeseros`)
    REFERENCES `db01restaurante`.`Meseros` (`idMeseros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db01restaurante`.`Ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db01restaurante`.`Ordenes` (
  `idOrdenes` INT NOT NULL AUTO_INCREMENT,
  `fechaOrdenes` DATETIME NOT NULL,
  `totalCuenta` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Mesas_idMesas` INT NOT NULL,
  PRIMARY KEY (`idOrdenes`, `Clientes_idClientes`, `Mesas_idMesas`),
  UNIQUE INDEX `idOrdenes_UNIQUE` (`idOrdenes` ASC) VISIBLE,
  INDEX `fk_Ordenes_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Ordenes_Mesas1_idx` (`Mesas_idMesas` ASC) VISIBLE,
  CONSTRAINT `fk_Ordenes_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `db01restaurante`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordenes_Mesas1`
    FOREIGN KEY (`Mesas_idMesas`)
    REFERENCES `db01restaurante`.`Mesas` (`idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db01restaurante`.`Platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db01restaurante`.`Platos` (
  `idPlatos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `precio` INT NOT NULL,
  `Ordenes_idOrdenes` INT NOT NULL,
  `Ordenes_Clientes_idClientes` INT NOT NULL,
  `Ordenes_Mesas_idMesas` INT NOT NULL,
  PRIMARY KEY (`idPlatos`, `Ordenes_idOrdenes`, `Ordenes_Clientes_idClientes`, `Ordenes_Mesas_idMesas`),
  UNIQUE INDEX `idPlatos_UNIQUE` (`idPlatos` ASC) VISIBLE,
  INDEX `fk_Platos_Ordenes1_idx` (`Ordenes_idOrdenes` ASC, `Ordenes_Clientes_idClientes` ASC, `Ordenes_Mesas_idMesas` ASC) VISIBLE,
  CONSTRAINT `fk_Platos_Ordenes1`
    FOREIGN KEY (`Ordenes_idOrdenes` , `Ordenes_Clientes_idClientes` , `Ordenes_Mesas_idMesas`)
    REFERENCES `db01restaurante`.`Ordenes` (`idOrdenes` , `Clientes_idClientes` , `Mesas_idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
