-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 11:07:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db02universidad
-- -----------------------------------------------------
-- EJERCICIO EN CLASE: CREAR UN ERD UNIVERSIDAD
-- 
-- La Universidad de programacion requiere realizar una base de datos donde puede llevar el control de lo siguiente, teniendo en cuenta que un campus tiene muchas carreras y que un alumno puedo pertenecer a una carrera:
-- 
-- Campus:
--   Nombre
--   Descripción
--   Dirección
-- 
-- Carrera:
--   Nombre
--   Descripción
-- 
-- Alumnos:
--   Nompre
--   Apellido paterno
--   Apellido materno
--   Fecha de nacimiento
--   Rut
--   Dirección
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db02universidad` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db02universidad` ;

-- -----------------------------------------------------
-- Table `db02universidad`.`Campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02universidad`.`Campus` (
  `idCampus` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCampus`),
  UNIQUE INDEX `idCampus_UNIQUE` (`idCampus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db02universidad`.`Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02universidad`.`Carreras` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `Campus_idCampus` INT NOT NULL,
  PRIMARY KEY (`idCarrera`, `Campus_idCampus`),
  UNIQUE INDEX `idCarrera_UNIQUE` (`idCarrera` ASC) VISIBLE,
  INDEX `fk_Carreras_Campus1_idx` (`Campus_idCampus` ASC) VISIBLE,
  CONSTRAINT `fk_Carreras_Campus1`
    FOREIGN KEY (`Campus_idCampus`)
    REFERENCES `db02universidad`.`Campus` (`idCampus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db02universidad`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02universidad`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `Carreras_idCarrera` INT NOT NULL,
  PRIMARY KEY (`idAlumnos`, `Carreras_idCarrera`),
  UNIQUE INDEX `idAlumnos_UNIQUE` (`idAlumnos` ASC) VISIBLE,
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC) VISIBLE,
  INDEX `fk_Alumnos_Carreras1_idx` (`Carreras_idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_Carreras1`
    FOREIGN KEY (`Carreras_idCarrera`)
    REFERENCES `db02universidad`.`Carreras` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
