-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 12:50:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db03agencia
-- -----------------------------------------------------
-- EJERCICIO EN CLASE: CREAR UN ERD AGENCIA DE EVENTO
-- 
-- Se requiere realizar un programa que permita a una agencia administrar lo siguiente:
-- 
-- Eventos:
--   Nombre evento
--   Descripción
-- 
-- Encargado:
--   Nombre
--   Apellido paterno
--   Apellido materno
--   Rut
-- 
-- Cliente:
--   Nombre
--   Apellido paterno
--   Apellido materno
--   Rut
--   Teléfono
--   Email
-- 
-- Salones de fiestas:
--   Nombre
--   Descripción
--   Dirección
-- 
-- Eventos proximos:
--   Fecha de nacimiento
--   Hora de inicio
--   Costo final
--   Eventos
--   Encargado
--   Clientes
--   Salon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db03agencia` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db03agencia` ;

-- -----------------------------------------------------
-- Table `db03agencia`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db03agencia`.`Eventos` (
  `idEventos` INT NOT NULL AUTO_INCREMENT,
  `nombreEvento` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idEventos`),
  UNIQUE INDEX `idEventos_UNIQUE` (`idEventos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db03agencia`.`Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db03agencia`.`Encargado` (
  `idEncargado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idEncargado`),
  UNIQUE INDEX `idEncargado_UNIQUE` (`idEncargado` ASC) VISIBLE,
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db03agencia`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db03agencia`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db03agencia`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db03agencia`.`Salon` (
  `idSalon` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSalon`),
  UNIQUE INDEX `idSalon_UNIQUE` (`idSalon` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db03agencia`.`EventosProximos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db03agencia`.`EventosProximos` (
  `idEventosProximos` INT NOT NULL AUTO_INCREMENT,
  `fechaEvento` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `costoFinal` INT NOT NULL,
  `Eventos_idEventos` INT NOT NULL,
  `Salon_idSalon` INT NOT NULL,
  `Encargado_idEncargado` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEventosProximos`, `Eventos_idEventos`, `Salon_idSalon`, `Encargado_idEncargado`, `Cliente_idCliente`),
  UNIQUE INDEX `idEventosProximos_UNIQUE` (`idEventosProximos` ASC) VISIBLE,
  INDEX `fk_EventosProximos_Eventos_idx` (`Eventos_idEventos` ASC) VISIBLE,
  INDEX `fk_EventosProximos_Salon1_idx` (`Salon_idSalon` ASC) VISIBLE,
  INDEX `fk_EventosProximos_Encargado1_idx` (`Encargado_idEncargado` ASC) VISIBLE,
  INDEX `fk_EventosProximos_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_EventosProximos_Eventos`
    FOREIGN KEY (`Eventos_idEventos`)
    REFERENCES `db03agencia`.`Eventos` (`idEventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventosProximos_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `db03agencia`.`Salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventosProximos_Encargado1`
    FOREIGN KEY (`Encargado_idEncargado`)
    REFERENCES `db03agencia`.`Encargado` (`idEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventosProximos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `db03agencia`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
